name: 'Setup Sherif'
description: 'Setup and run Sherif, an opinionated, zero-config linter for JavaScript monorepos'

inputs:
  version:
    description: 'The Sherif version to use (e.g., v1.1.0)'
    required: false
    default: 'latest'
  github-token:
    description: 'GitHub token for API requests'
    required: false
    default: ${{ github.token }}
  args:
    description: 'Additional arguments to pass to Sherif'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'action/index.js'

branding:
  icon: 'shield'
  color: 'orange'
